CREATE TABLE USER_OPS_ENTITY (
    PERSONNEL_ID BIGINT NOT NULL,
    COMPANY_ID VARCHAR(255) NOT NULL,
    OPS_ENTITY_ID VARCHAR(255) NOT NULL,
    OPS_COMPANY_ID VARCHAR(255),
    ADMIN_ROLE VARCHAR(50),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (PERSONNEL_ID, COMPANY_ID, OPS_ENTITY_ID)
);

INSERT INTO USER_OPS_ENTITY (PERSONNEL_ID, COMPANY_ID, OPS_ENTITY_ID, OPS_COMPANY_ID, ADMIN_ROLE) VALUES
(1001, 'COMP001', 'OPS001', 'OPSCOMP001', 'ADMIN'),
(1002, 'COMP001', 'OPS002', 'OPSCOMP001', 'USER'),
(1003, 'COMP002', 'OPS003', 'OPSCOMP002', 'MANAGER');
